apiVersion: v1
kind: Service
metadata:
  name: spring-boot-docker
  labels:
    app: spring-boot-docker
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: spring-boot-docker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-docker
  template:
    metadata:
      labels:
        app: spring-boot-docker
    spec:
      containers:
        - name: myapp
          image: image-registry.openshift-image-registry.svc:5000/tekton-demo/spring-boot-docker:v1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http